export const florestSound = new Audio('./assets/Floresta.wav')
export const rainSound = new Audio('./assets/Chuva.wav')
export const cafeSound = new Audio('./assets/Cafeteria.wav')
export const burnSound = new Audio('./assets/Lareira.wav')
export const kichentimer = new Audio('./assets/kichen-timer.mp3')